addSbtPlugin("com.jsuereth"      % "sbt-pgp"         % "1.0.0")
addSbtPlugin("com.github.gseitz" % "sbt-release"     % "1.0.0")
addSbtPlugin("io.spray" 	 % "sbt-boilerplate" % "0.5.9")
addSbtPlugin("org.scoverage" 	 % "sbt-scoverage"   % "1.3.3")
addSbtPlugin("org.scalariform" 	 % "sbt-scalariform" % "1.5.1")
addSbtPlugin("org.xerial.sbt" 	%  "sbt-sonatype"    % "1.1")
